# Generated by Django 5.0.2 on 2024-02-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
